### ISSUE TITLE
Verificator raises segfault

### ISSUE THREAD

**Issue by AndreyBritvin** [coffee8cat/stack#7]
```
stack_t stack = {INIT(stack)};
stack_init(&stack, 13);
stack_push(&stack, 20);
stack_init(&stack, INT_MAX - 5);
stack.err_stat = OK;
stack.data = (stack_elem_t *) NULL + 2;
stack_push(&stack, 30);
```
This code raise segfault because you check data canary before checking hash sum
Stack.data changed, hash changed, but you stack.data[left_canary] before check hash

**Comment by coffee8cat** [comment]
So final boss fell... Congratulations then
